#checks if the output contains the line for 4222
#[5.989403, 49.508464]}, "properties": {"postcode": "4222"
#mini check because exit code from grep will be > 1 if it doesn't work

language: python
sudo: required
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python postcode-centroid.py | grep "5.989.*, 49.508.*postcode.*\"4222\"" > /dev/null
notifications:
  email:
    on_success: never 
    on_failure: always